#!/usr/bin/env python
import os, sys
if sys.version_info < (3, 0):
    reload(sys)
    sys.setdefaultencoding("utf-8")
    path = os.getcwdu()
else:
    path = os.getcwd()
path = path.replace(os.environ["HOME"],"~")
dirs = path.split("/");
for i in range(len(dirs) - 1):
    if not dirs[i]:
        continue
    if dirs[i][0] == '.':
        dirs[i] = dirs[i][:2]
    else:
        dirs[i] = dirs[i][:1]
print("/".join(dirs))
